[tool.nbqa.addopts]
flake8 = [
    "--ignore=E501,W503,E203,E402"
]
[tool.pytest.ini_options]
addopts = "--ignore-glob=Untitled* --ignore=snippets.ipynb --ignore=newspaper-explorer.ipynb --ignore-glob=App* --ignore-glob=draft* --ignore-glob=python-basics* --ignore=appmode-checking.ipynb"